[build]
  command = """
    pip install pygbag==0.8.2 &&
    python -m pygbag --app-name flappybird --cdn "https://pygame-web.github.io/archives/0.9/" --python 3.11 --build main.py
  """
  publish = "build/web"

[build.environment]
  PYTHONPATH = "."
