[build]
  command = """
    pip install pygbag==0.8.2 &&
    python -m pygbag \
      --app_name flappybird \
      --cdn "https://pygame-web.github.io/archives/0.9/" \
      --template web/index.html \
      --build \
      --archive \
      main.py
  """
  publish = "build/web"

[build.environment]
  PYTHONPATH = "."
  PYTHON_VERSION = "3.11"
